x-service-defaults: &service-defaults
  user: root
  environment:
    TZ: Asia/Seoul
    SPRING_CONFIG_IMPORT: configserver:http://config:8888
  networks:
    - platform_default
    - grafana_default
  deploy: &deploy-defaults
    replicas: 1
    update_config:
      parallelism: 1
      order: stop-first
      failure_action: rollback
      monitor: 3m
    rollback_config:
      parallelism: 1
      order: stop-first
      failure_action: pause
      monitor: 3m
    restart_policy:
      condition: any
      delay: 5s

services:
  lotto:
    <<: *service-defaults
    image: ghcr.io/now-start/lotto-service:9.4.0

  coin:
    <<: *service-defaults
    image: ghcr.io/now-start/evergreen:2.2.0
    deploy:
      <<: *deploy-defaults
      placement:
        constraints:
          - node.hostname == NOW_START

networks:
  platform_default:
    external: true
  grafana_default:
    external: true
