services:
  bitwarden:
    image: vaultwarden/server:1.37.3
    ports:
      - target: 80
        published: 1080
        protocol: tcp
        mode: ingress
    environment:
      TZ: Asia/Seoul
      DOMAIN: https://bitwarden.nowstart.org
      SSO_ENABLED: "true"
      SSO_ONLY: "true"
      SSO_AUTH_ONLY_NOT_SESSION: "true"
      SSO_AUTHORITY: https://sso.nowstart.org/webman/sso
      SSO_CLIENT_ID: "1db429ff8c99accb53cdf5d989e70c91"
      SSO_CLIENT_SECRET: ${BITWARDEN_SSO_CLIENT_SECRET:-}
    volumes:
      - bitwarden_data:/data
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 3m
      rollback_config:
        parallelism: 1
        order: stop-first
        failure_action: pause
        monitor: 3m
      restart_policy:
        condition: any
        delay: 5s

networks:
  default:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: "1200"

volumes:
  bitwarden_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=100.100.1.1,vers=4,hard
      device: :/volume1/docker/bitwarden
