services:
  flame:
    image: pawelmalak/flame:latest
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: ingress
    environment:
      TZ: Asia/Seoul
      PASSWORD: ${FLAME_PASSWORD:-}
    volumes:
      - flame_data:/app/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  flame_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.8.0.1,vers=4,hard
      device: :/volume1/docker/flame
