services:
  nyang-nyang-bot:
    image: ghcr.io/now-start/nyang-nyang-bot:5.9.9
    user: root
    environment:
      TZ: Asia/Seoul
      SPRING_CONFIG_IMPORT: configserver:http://config:8888
    volumes:
      - chzzk_data:/workspace/key
    networks:
      - platform_default
      - grafana_default
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        monitor: 3m
      rollback_config:
        parallelism: 1
        order: stop-first
        failure_action: pause
        monitor: 3m
      restart_policy:
        condition: any
        delay: 5s

volumes:
  chzzk_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=100.100.1.1,vers=4,hard
      device: :/volume1/docker/chzzk

networks:
  platform_default:
    external: true
  grafana_default:
    external: true
