x-deploy-defaults: &deploy-defaults
  update_config:
    parallelism: 1
    order: stop-first
    failure_action: rollback
    monitor: 3m
  rollback_config:
    parallelism: 1
    order: stop-first
    failure_action: pause
    monitor: 3m
  restart_policy:
    condition: any
    delay: 5s

x-global-deploy-defaults: &global-deploy-defaults
  <<: *deploy-defaults
  mode: global
  placement:
    constraints:
      - node.platform.arch == x86_64

x-service-defaults: &service-defaults
  user: root
  environment:
    TZ: Asia/Seoul
    SPRING_CONFIG_IMPORT: configserver:http://config:8888
  networks:
    - default
    - grafana_default
  deploy:
    <<: *deploy-defaults
    mode: replicated
    replicas: 1

services:
  config:
    <<: *service-defaults
    image: ghcr.io/now-start/config:2.1.15
    deploy:
      <<: *global-deploy-defaults
    environment:
      TZ: Asia/Seoul
      ENCRYPT_KEY: ${SPRING_ENCRYPT_KEY:-}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/

  eureka:
    <<: *service-defaults
    image: ghcr.io/now-start/eureka:2.4.10

  admin:
    <<: *service-defaults
    image: ghcr.io/now-start/admin:2.11.9

  gateway:
    <<: *service-defaults
    image: ghcr.io/now-start/gateway:6.1.1
    deploy:
      <<: *global-deploy-defaults
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    environment:
      TZ: Asia/Seoul
      JAVA_TOOL_OPTIONS: -XX:MaxDirectMemorySize=256m
      SPRING_CONFIG_IMPORT: configserver:http://config:8888

networks:
  default:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: "1200"
  grafana_default:
    external: true
